Be more careful about existing EUPS installations

diff --git a/bin/bootstrap_mhs b/bin/bootstrap_mhs
--- a/bin/bootstrap_mhs
+++ b/bin/bootstrap_mhs
@@ -3,19 +3,23 @@
 usage()
 {
     (
-       echo "usage: $0: [-r root-directory] [-U]\n"
-       echo "    -U  - use existing EUPS product tree."
+       echo "usage: $0: [-r root-directory] [-U] [-V TAG]\n"
+       echo "    -U      - use existing EUPS product tree."
+       echo "    -V TAG  - use specified git tag for our products."
        echo "    If no root directory is specified, use $ICS_ROOT\n" 
     ) >&2
     exit 1
 }
 
 ICS_ROOT=$HOME/mhs
+ICS_TAG=master
 while getopts :hU?r: arg; do
     case $arg in
        r) ICS_ROOT="$OPTARG"
            ;; 
        U) addToEups=1
+           ;; 
+       V) ICS_TAG="$OPTARG"
            ;; 
        ?) echo "unknown argument: $OPTARG"
           usage
@@ -69,12 +73,22 @@ if type eups >/dev/null 2>&1; then
     fi
     unset EUPS_VERSION
 else
-    if test -n "$EUPS_PATH" || test -n "$EUPS_DIR"; then
-        echo "I cannot find eups, but a EUPS_PATH=$EUPS_PATH or an EUPS_DIR=$EUPS_DIR is defined."
+    if test -n "$EUPS_DIR"; then
+        echo
+        echo "I cannot find eups, but an EUPS_DIR=$EUPS_DIR is defined."
         echo "Not sure what is safe to do, so am stopping now."
         exit 1
     fi
-    EUPS_VERSION=1.2.33
+    EUPS_VERSION=${EUPS_BOOTSTRAP_VERSION:-"1.2.33"}
+    EUPS_INSTALL_DIR=$EUPS_PATH/eups/$EUPS_VERSION
+    EUPS_DEFAULT_DIR=$EUPS_PATH/eups/default
+
+    if test -e "$EUPS_INSTALL_DIR" || test -e "$EUPS_DEFAULT_DIR"; then
+        echo
+        echo "Either $EUPS_INSTALL_DIR or $EUPS_DEFAULT_DIR exists."
+        echo "Not sure what is safe to do, so am stopping now."
+        exit 1
+    fi
 fi
 
 # 4. The ICS pieces we want to install, in order. 
@@ -88,7 +102,6 @@ ICS_DEVEL_PRODUCTS="ics_mhs_actorcore
                     ics_mhs_pficsActor
                     ics_mhs_root"
 
-ICS_BOOTSTRAP_VERSION=1.5
 #################################
 
 mkdir -p $ICS_ROOT || (echo "could not create $ICS_ROOT directory!"; exit 1)
@@ -98,27 +111,23 @@ cd $ICS_DEVEL_ROOT
 # Do we need to bootstrap a eups version?
 if test -n "$EUPS_VERSION"; then 
     echo 
-    echo "######## installing eups...."
+    echo "######## installing eups (version=$EUPS_VERSION) to $EUPS_INSTALL_DIR ...."
     git clone -b $EUPS_VERSION https://github.com/RobertLuptonTheGood/eups.git eups 
-    (cd eups 
-        ./configure --with-eups=$EUPS_PATH --prefix=$EUPS_PATH/eups --disable-docs
-        make install)
-    source $EUPS_PATH/eups/bin/setups.sh
 
-    # Now that we have a eups to tell us things, reinstall to the proper path.
-    eupsPrefix=$(eups path)/$(eups flavor)/eups/$EUPS_VERSION
     (cd eups 
-        ./configure --with-eups=$EUPS_PATH --prefix=$eupsPrefix
+        ./configure --with-eups=$EUPS_PATH --prefix=$EUPS_INSTALL_DIR
         make install
-        make declare
-        eups declare -c eups $EUPS_VERSION
     )
+    if test $? -ne 0; then 
+        echo "Failed to install eups."
+        exit 1
+    fi
 
-    # Shuffle links around
-    mv $EUPS_PATH/eups $EUPS_PATH/eups-bootstrap
-    ln -s $eupsPrefix $EUPS_PATH/eups
+    # Make convenience link, for logins, etc.
+    ln -s $EUPS_VERSION $EUPS_DEFAULT_DIR
 
-    setup -v eups
+    # Act as if we are logging in.
+    source $EUPS_DEFAULT_DIR/bin/setups.sh
 fi
 
 # Clean out any possible crud in the environment
@@ -134,7 +143,7 @@ if test -n "$(eups list -q -s ics_mhs_config)" && test -d "$ICS_MHS_CONFIG_DIR";
     echo "the ics_mhs_config product is already setup. We'll use that enviroment and not overwrite it." >&2
 else
     cd $ICS_DEVEL_ROOT          # to be safe.
-    git clone gitolite@pfs.ipmu.jp:ics_mhs_config
+    git clone -b $ICS_TAG gitolite@pfs.ipmu.jp:ics_mhs_config
     ( cd ics_mhs_config;
         setup -r .
         sed "s;%(ICS_ROOT);$ICS_ROOT;g" < ups/ics_mhs_config.table-in > ups/ics_mhs_config.table
@@ -155,10 +164,10 @@ for p in $ICS_DEVEL_PRODUCTS; do
     echo "######## installing a live (git) version of ${p}..."
 
     cd $ICS_DEVEL_ROOT          # to be safe.
-    git clone gitolite@pfs.ipmu.jp:$p
+    git clone -b $ICS_TAG gitolite@pfs.ipmu.jp:$p
     ( cd $p;
-        eups declare -v -F -r $PWD $p git
-        eups declare -v -c $p git
+        eups declare -v -F -r $PWD $p $ICS_TAG
+        eups declare -v -c $p $ICS_TAG
     )
     setup -v $p
 done
